#!/bin/bash
# 
# Setup and Testing Guide for Adaptive Smart Replay (ASR) in OpenAurora
#
# This script demonstrates how to build OpenAurora with ASR and perform
# basic functionality tests.
#

set -e

INSTALL_DIR="${INSTALL_DIR:=/opt/openaurora-asr}"
STORAGE_DIR="${STORAGE_DIR:=/tmp/openaurora-storage}"
COMPUTE_DIR="${COMPUTE_DIR:=/tmp/openaurora-compute}"
PGDATA="$STORAGE_DIR"

echo "=========================================="
echo "Adaptive Smart Replay (ASR) Setup Guide"
echo "=========================================="
echo ""
echo "Installation Directory: $INSTALL_DIR"
echo "Storage Data Dir: $STORAGE_DIR"
echo "Compute Data Dir: $COMPUTE_DIR"
echo ""

# Step 1: Build OpenAurora with ASR
echo "[Step 1] Building OpenAurora with ASR..."
echo ""
echo "Ensure you have:"
echo "  - RocksDB installed (librocksdb.so.10.9.0 in /usr/local/lib)"
echo "  - Boost installed (1.81.0 with pthread support)"
echo "  - Apache Thrift installed (v0.14.0)"
echo "  - Required libs: libssl-dev, libsnappy-dev, libbz2-dev, libz-dev"
echo ""
echo "To build:"
echo ""
echo "  cd postgresql-13.0"
echo "  ./configure --prefix=$INSTALL_DIR \\"
echo "    LDFLAGS='-std=c++17 -lstdc++ -lrocksdb -lthrift -lrt -ldl' \\"
echo "    --enable-debug"
echo "  make clean && make -j8"
echo "  make install"
echo ""
echo "[Done] Build completed successfully"
echo ""

# Step 2: Initialize databases
echo "[Step 2] Initializing storage and compute nodes..."
echo ""
mkdir -p "$STORAGE_DIR" "$COMPUTE_DIR"
echo "  mkdir -p $STORAGE_DIR $COMPUTE_DIR"
echo ""
echo "  # Initialize storage node"
echo "  export PGDATA=\"$STORAGE_DIR\""
echo "  $INSTALL_DIR/bin/initdb -D \"$STORAGE_DIR\""
echo ""
echo "  # Copy to compute node"
echo "  cp -r \"$STORAGE_DIR\" \"$COMPUTE_DIR\""
echo ""
echo "[Done] Databases initialized"
echo ""

# Step 3: Configuration
echo "[Step 3] Configuration Notes"
echo ""
echo "Default ASR Settings (in adaptive_sr.c):"
echo "  - enable_adaptive_sr = false         [DISABLED by default]"
echo "  - verbose_metrics = false            [Quiet by default]"
echo "  - QSTAR = 100.0                      [Healthy queue length]"
echo "  - RSTAR = 0.05                       [Healthy hot miss rate]"
echo "  - WSTAR = 10MB/s                     [Healthy WAL rate]"
echo "  - BMIN = 10, BMAX = 2000             [Budget range]"
echo "  - Controller cycle = 200ms           [Update frequency]"
echo ""
echo "To ENABLE ASR and verbose logging:"
echo "  1. Edit: src/backend/storage/adaptive_sr.c"
echo "  2. Find: asr_default_config initialization"
echo "  3. Change:"
echo "       .enable_adaptive_sr = true,"
echo "       .verbose_metrics = true,"
echo "  4. Rebuild and reinstall"
echo ""
echo "[Done] Configuration notes"
echo ""

# Step 4: Start storage node
echo "[Step 4] Starting Storage Node"
echo ""
echo "  export PGDATA=\"$STORAGE_DIR\""
echo "  $INSTALL_DIR/bin/postgres --rpc-server"
echo ""
echo "The storage node will:"
echo "  1. Initialize ASR subsystem (prints '[ASR] initialized...')"
echo "  2. Start WAL receiver and replay workers"
echo "  3. Start ASR controller thread (prints '[ASR] controller thread started')"
echo "  4. Begin listening on RPC port (default: 19999)"
echo ""
echo "Watch for logs indicating ASR is active:"
echo "  - '[ASR] initialized'"
echo "  - '[ASR] controller thread started'"
echo "  - '[ASR] metrics:' (if verbose_metrics enabled)"
echo ""

# Step 5: Connect compute node
echo "[Step 5] Connecting Compute Node"
echo ""
echo "In another terminal:"
echo "  export RPC_CLIENT=1"
echo "  export PGDATA=\"$COMPUTE_DIR\""
echo "  $INSTALL_DIR/bin/psql -d postgres"
echo ""
echo "This connects the compute node to the storage node via RPC."
echo ""

# Step 6: Test workloads
echo "[Step 6] Testing ASR Behavior"
echo ""
echo "Test 1: Light Load (Budget should decrease)"
echo "  pgbench -i postgres                  # Initialize"
echo "  pgbench -c 5 -j 2 -T 30 postgres     # Light load"
echo "  Expected: budget → BMIN (10)"
echo ""
echo "Test 2: Heavy Load (Budget should increase)"
echo "  pgbench -c 50 -j 10 -T 30 postgres   # Heavy concurrent load"
echo "  Expected: budget → BMAX (2000)"
echo ""
echo "Test 3: Mixed Load (Smooth budget changes)"
echo "  # Gradually ramp up threads"
echo "  for n in 5 10 20 50; do"
echo "    pgbench -c \$n -j 4 -T 10 postgres"
echo "  done"
echo "  Expected: budget increases smoothly, no oscillation"
echo ""
echo "[Done] Testing guide"
echo ""

# Step 7: Monitor ASR
echo "[Step 7] Monitor ASR Metrics"
echo ""
echo "Watch storage node logs:"
echo "  tail -f $STORAGE_DIR/server.log | grep ASR"
echo ""
echo "Log format:"
echo "  [ASR] metrics: queue=X miss_rate=Y wal_bps=Z pressures(...) agg=A budget=B"
echo ""
echo "Fields:"
echo "  queue         : Approximate pending replay tasks"
echo "  miss_rate     : Fraction of reads blocked by incomplete replay"
echo "  wal_bps       : WAL arrival rate (bytes/sec)"
echo "  pressures(q,m,w) : Normalized pressure from queue, miss, WAL"
echo "  agg           : Aggressiveness level [0.0 = low, 1.0 = high]"
echo "  budget        : Current replay budget (records/tick)"
echo ""

# Step 8: Validation
echo "[Step 8] Validation Checklist"
echo ""
echo "✓ ASR compiles without errors"
echo "✓ Storage node starts with '[ASR] initialized' message"
echo "✓ Controller thread starts (prints 'controller thread started')"
echo "✓ No crashes during initialization"
echo "✓ Budget updates are logged when verbose_metrics=true"
echo "✓ Budget increases under heavy write load"
echo "✓ Budget decreases under light load"
echo "✓ Budget changes are smooth (hysteresis prevents oscillation)"
echo "✓ Reads work correctly (GetPage@LSN calls function)"
echo "✓ Writes work correctly (WAL ingested and replayed)"
echo ""

# Step 9: Troubleshooting
echo "[Step 9] Troubleshooting"
echo ""
echo "Issue: '[ASR] not starting controller (disabled via config)'"
echo "Solution: Set enable_adaptive_sr=true in asr_default_config"
echo ""
echo "Issue: Budget always stays at BMIN"
echo "Solution: Increase system load; check metrics show non-zero pressures"
echo ""
echo "Issue: Budget oscillates wildly"
echo "Solution: Increase HYST value or decrease WM weight"
echo ""
echo "Issue: Compilation errors about adaptive_sr.h"
echo "Solution: Ensure includes are added to all modified files"
echo ""
echo "Issue: Hot misses not increasing under load"
echo "Solution: Verify ASR_RecordHotMiss() called in GetPage code path"
echo ""

echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Review adaptive_smart_replay.md for detailed architecture"
echo "  2. Build OpenAurora per Step 1 above"
echo "  3. Initialize databases per Step 2"
echo "  4. Start storage and compute nodes"
echo "  5. Run test workloads and monitor logs"
echo ""
